# Generated by Django 3.1.3 on 2020-12-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='food_pics'),
        ),
    ]
