# Generated by Django 3.1.3 on 2020-12-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201203_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='type',
            field=models.CharField(choices=[('Śniadania', 'Sniadania'), ('Lunche', 'Lunche'), ('Zupy', 'Zupy'), ('Sałatki', 'Salatki'), ('Surówki', 'Surowki'), ('Ciasta', 'Ciasta'), ('Obiady', 'Obiady'), ('Dodatki', 'Dodatki'), ('Podwieczorki', 'Podwieczorki'), ('Kolacje', 'Kolacje')], max_length=12),
        ),
    ]
